services:
  app:
    build:
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER =root
      - MYSQL_PASSWORD=iir4
      - MYSQL_DB=todos
    command: sh -c "yarn install && yarn run dev"
    depends-on:
      - db
  db:
    images: mysql:5.7
    environnements:
      - MYSQL_ROOT_PASSWORD=iir4
      - MYSQL_DATABASE=todos
    volumes:
      - todo-mysql-data:/var/lib/mysql

volumes:
  todo-mysql-data:
